import copy
import html
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


def substitute_names(transcript: dict, speaker_names: dict) -> dict:
    """
    Return a deep copy of transcript with speaker IDs replaced by display names.
    Utterances with no matching name keep their original ID label ("Speaker A" etc.).
    """
    out = copy.deepcopy(transcript)
    for utt in out.get("utterances", []):
        sid = utt["speaker"]
        utt["speaker"] = speaker_names.get(sid) or f"Speaker {sid}"
    return out


def build_pdf(transcript: dict) -> bytes:
    """
    Render a clean PDF of the transcript using reportlab.

    Pass the result of substitute_names() — speaker IDs must already be
    replaced with display names before calling this function.

    Returns raw PDF bytes suitable for st.download_button.
    """
    title    = transcript.get("_title", "Debate")
    date_str = datetime.now().strftime("%Y-%m-%d")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=20 * mm, bottomMargin=20 * mm,
    )

    base  = getSampleStyleSheet()
    h1    = ParagraphStyle("h1",   parent=base["Heading1"], fontSize=15, spaceAfter=4)
    sub   = ParagraphStyle("sub",  parent=base["Italic"],   fontSize=9,  spaceAfter=10)
    body  = ParagraphStyle("body", parent=base["Normal"],   fontSize=11, spaceAfter=3)
    muted = ParagraphStyle("muted", parent=body, textColor=colors.grey)

    story = [
        Paragraph(html.escape(f"Debate Transcript — {title}"), h1),
        Paragraph(html.escape(f"Generated by SayWhat  |  {date_str}"), sub),
        Spacer(1, 4 * mm),
    ]

    for utt in transcript.get("utterances", []):
        name = html.escape(utt["speaker"])
        ts   = _ms_to_ts(utt["start_ms"])
        text = html.escape(utt.get("text", ""))
        flag = utt.get("flag", "ok")

        line = f"[{ts}] {name}: {text}"
        if flag in ("uncertain", "unreliable"):
            line += "  (low confidence)"

        story.append(Paragraph(line, muted if flag == "unreliable" else body))
        story.append(Spacer(1, 1 * mm))

    doc.build(story)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _ms_to_ts(ms: int) -> str:
    s = ms // 1000
    return f"{s // 60:02d}:{s % 60:02d}"
