import copy
from datetime import datetime

from fpdf import FPDF


def substitute_names(transcript: dict, speaker_names: dict) -> dict:
    """
    Return a deep copy of transcript with speaker IDs replaced by display names.
    Utterances with no matching name keep their original ID label ("Speaker A" etc.).
    """
    out = copy.deepcopy(transcript)
    for utt in out.get("utterances", []):
        sid = utt["speaker"]
        utt["speaker"] = speaker_names.get(sid) or f"Speaker {sid}"
    return out


def build_pdf(transcript: dict, speaker_names: dict) -> bytes:
    """
    Render a clean PDF of the transcript using fpdf2.

    Layout:
        - Title:    "Debate Transcript — {title}"
        - Subtitle: "Generated by Debate Fact-Checker · {date}"
        - Body:     one paragraph per utterance: "[MM:SS] Name: text"
                    flagged utterances append "(low confidence)"

    Uses Helvetica (built-in core font). Characters outside Latin-1
    are replaced with '?' to avoid encoding errors.

    Returns raw PDF bytes suitable for st.download_button.
    """
    title    = transcript.get("_title", "Debate")
    date_str = datetime.now().strftime("%Y-%m-%d")

    pdf = FPDF()
    pdf.set_margins(20, 20, 20)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 15)
    pdf.multi_cell(0, 9, _l1(f"Debate Transcript — {title}"))

    # Subtitle
    pdf.set_font("Helvetica", "I", 9)
    pdf.multi_cell(0, 6, f"Generated by SayWhat  \xb7  {date_str}")
    pdf.ln(6)

    # Body
    pdf.set_font("Helvetica", "", 11)
    for utt in transcript.get("utterances", []):
        sid  = utt["speaker"]
        name = speaker_names.get(sid) or f"Speaker {sid}"
        ts   = _ms_to_ts(utt["start_ms"])
        text = _l1(utt.get("text", ""))
        flag = utt.get("flag", "ok")

        line = f"[{ts}] {name}: {text}"
        if flag in ("uncertain", "unreliable"):
            line += "  (low confidence)"

        pdf.multi_cell(0, 7, line)
        pdf.ln(1)

    return bytes(pdf.output())


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _ms_to_ts(ms: int) -> str:
    s = ms // 1000
    return f"{s // 60:02d}:{s % 60:02d}"


def _l1(text: str) -> str:
    """Replace characters outside Latin-1 so Helvetica renders without errors."""
    return text.encode("latin-1", errors="replace").decode("latin-1")
